/* Generated by CS-Cart.ie */
function addScript(src) {
    const scriptElement = document.createElement('script');
    scriptElement.setAttribute('src', src);
    document.body.appendChild(scriptElement);
}

fetch('index.php?dispatch=freichat.get_fc_url')
    .then(response => response.json())
    .then(data => {
        if (data.url) {
            const url = data.url;
            addScript(url);
        }
    });